<?php

namespace ContainerUK3x7YP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QDzC5l2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qDzC5l2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qDzC5l2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'guestbook' => ['privates', '.errored..service_locator.qDzC5l2.App\\Entity\\Guestbook', NULL, 'Cannot autowire service ".service_locator.qDzC5l2": it references class "App\\Entity\\Guestbook" but no such service exists.'],
            'guestbookRepository' => ['privates', 'App\\Repository\\GuestbookRepository', 'getGuestbookRepositoryService', true],
        ], [
            'guestbook' => 'App\\Entity\\Guestbook',
            'guestbookRepository' => 'App\\Repository\\GuestbookRepository',
        ]);
    }
}
