<?php

namespace ContainerUK3x7YP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuestbookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qDzC5l2.App\Entity\Guestbook' shared service.
     *
     * @return \App\Entity\Guestbook
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qDzC5l2": it references class "App\\Entity\\Guestbook" but no such service exists.');
    }
}
