<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUK3x7YP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUK3x7YP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUK3x7YP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUK3x7YP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUK3x7YP\App_KernelDevDebugContainer([
    'container.build_hash' => 'UK3x7YP',
    'container.build_id' => '479b2759',
    'container.build_time' => 1673555204,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUK3x7YP');
