<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_guestbook_index' => [[], ['_controller' => 'App\\Controller\\GuestbookController::index'], [], [['text', '/guestbook/']], [], [], []],
    'app_guestbook_new' => [[], ['_controller' => 'App\\Controller\\GuestbookController::new'], [], [['text', '/guestbook/new']], [], [], []],
    'app_guestbook_edit' => [['id'], ['_controller' => 'App\\Controller\\GuestbookController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/guestbook']], [], [], []],
    'app_guestbook_delete' => [['id'], ['_controller' => 'App\\Controller\\GuestbookController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/guestbook']], [], [], []],
    'app_guestbook_approve' => [['id', 'active'], ['_controller' => 'App\\Controller\\GuestbookController::approve'], [], [['text', '/approve'], ['variable', '/', '[^/]++', 'active', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/guestbook']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\GuestbookController::index'], [], [['text', '/']], [], [], []],
];
