<?php

namespace ContainerAQVXoUo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QtuDeFNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qtuDeFN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qtuDeFN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'guestbookService' => ['privates', 'App\\Service\\GuestbookService', NULL, 'Cannot autowire service "App\\Service\\GuestbookService": argument "$abstractController" of method "__construct()" references class "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController" but no such service exists. You should maybe alias this class to one of these existing services: "App\\Controller\\GuestbookController", "App\\Controller\\RegistrationController", "App\\Controller\\SecurityController", "App\\Security\\AccessDeniedHandler".'],
        ], [
            'guestbookService' => 'App\\Service\\GuestbookService',
        ]);
    }
}
