<?php

namespace ContainerAQVXoUo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessDeniedHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Security\AccessDeniedHandler' shared autowired service.
     *
     * @return \App\Security\AccessDeniedHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authorization/AccessDeniedHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/AccessDeniedHandler.php';

        $container->services['App\\Security\\AccessDeniedHandler'] = $instance = new \App\Security\AccessDeniedHandler();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Security\\AccessDeniedHandler', $container));

        return $instance;
    }
}
