<?php

namespace ContainerAQVXoUo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuestbookServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GuestbookService' shared autowired service.
     *
     * @return \App\Service\GuestbookService
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service "App\\Service\\GuestbookService": argument "$abstractController" of method "__construct()" references class "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController" but no such service exists. You should maybe alias this class to one of these existing services: "App\\Controller\\GuestbookController", "App\\Controller\\RegistrationController", "App\\Controller\\SecurityController", "App\\Security\\AccessDeniedHandler".');
    }
}
