vich_uploader:
  db_driver: orm # or mongodb or phpcr

  metadata:
    type: attribute

  mappings:
    guestbook:
      uri_prefix: /images/guestbook
      upload_destination: '%kernel.project_dir%/public/images/guestbook'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true